//! **Only the structs needed for CPI** – copy-paste from safe_pump
use anchor_lang::prelude::*;

// ---------------------------------------------------------------------
// 1. Account structs (exactly the same names / layout)
// ---------------------------------------------------------------------
#[account]
pub struct TokenContract {
    pub is_initialized: bool,
    pub total_supply: u64,
    pub treasury_wallet: Pubkey,
    pub swap_count: u64,
    pub total_swapped: u64,
    pub vault_sol_balance: u64,
    pub vault_token_balance: u64,
    pub burned_tokens: u64,
    pub burn_percentage: u8,
    pub bond_timestamp: i64,
    pub buy_cap_percentage: u64,
    pub liquidity_threshold_index: u8,
    pub friends_wallets: [Pubkey; 4],
    pub friends_amounts: [u64; 4],
    pub deployer_amount: u64,
    pub bump: u8,
    pub badge_mint: Option<Pubkey>,
    pub badge_master_edition: Option<Pubkey>,
}

#[account]
pub struct BadgeHolders {
    pub holders: [Pubkey; 1000],
    pub buy_swap_count: [(Pubkey, u64); 1000],
    pub holder_count: u64,
    pub bump: u8,
}

#[account]
pub struct UserSwapData {
    pub last_swap_timestamp: i64,
    pub last_cpi_timestamp: i64,
    pub cpi_count: u64,
    pub bump: u8,
    pub vault: Pubkey,
}

#[account]
pub struct RewardDistribution {
    pub swapper_rewards: [(Pubkey, u64); 1000],
    pub badge_rewards: u64,
    pub swap_count: u64,
    pub last_distribution_timestamp: i64,
    pub bump: u8,
}

#[account]
pub struct MemeCoinRegistry {
    pub entries: Vec<(Pubkey, Pubkey)>,
    pub bump: u8,
}

#[account]
pub struct AirdropRegistry {
    pub claimers: Vec<Pubkey>,
    pub bump: u8,
}

#[account]
pub struct Vault {
    pub bump: u8,
    pub nonce: u64,
    pub last_signer: Pubkey,
}

// ---------------------------------------------------------------------
// 2. CPI instruction signatures
// ---------------------------------------------------------------------
#[derive(AnchorSerialize, AnchorDeserialize)]
pub struct HandshakeArgs {
    pub meme_program_id: Pubkey,
}

#[derive(AnchorSerialize, AnchorDeserialize)]
pub struct GlobalTaxSwapArgs {
    pub amount: u64,
    pub is_buy: bool,
    pub meme_program_id: Pubkey,
}

#[derive(AnchorSerialize, AnchorDeserialize)]
pub struct TriggerAirdropArgs {
    pub meme_program_id: Pubkey,
}

// The actual CPI functions are generated by the `cpi` feature
#[cfg(feature = "cpi")]
pub mod cpi {
    use super::*;
    use anchor_lang::prelude::*;

    pub fn handshake<'info>(
        ctx: CpiContext<'_, '_, '_, 'info, Handshake<'info>>,
        meme_program_id: Pubkey,
    ) -> Result<()> {
        let ix = crate::instruction::Handshake { meme_program_id };
        let account_infos = ctx.accounts.into_account_infos();
        solana_program::program::invoke(&ix, &account_infos)
    }

    pub fn global_tax_swap<'info>(
        ctx: CpiContext<'_, '_, '_, 'info, GlobalTaxSwap<'info>>,
        amount: u64,
        is_buy: bool,
        meme_program_id: Pubkey,
    ) -> Result<()> {
        let ix = crate::instruction::GlobalTaxSwap { amount, is_buy, meme_program_id };
        let account_infos = ctx.accounts.into_account_infos();
        solana_program::program::invoke(&ix, &account_infos)
    }

    pub fn trigger_airdrop<'info>(
        ctx: CpiContext<'_, '_, '_, 'info, TriggerAirdrop<'info>>,
        meme_program_id: Pubkey,
    ) -> Result<()> {
        let ix = crate::instruction::TriggerAirdrop { meme_program_id };
        let account_infos = ctx.accounts.into_account_infos();
        solana_program::program::invoke(&ix, &account_infos)
    }
}

// ---------------------------------------------------------------------
// 3. Context structs (exactly the same layout as in safe_pump)
// ---------------------------------------------------------------------
#[derive(Accounts)]
pub struct Handshake<'info> {
    #[account(mut)]
    pub user: Signer<'info>,
    #[account(mut)]
    pub user_state: Account<'info, UserSwapData>,
    #[account(mut)]
    pub mint: Account<'info, Mint>,
    #[account(mut)]
    pub meme_mint: Account<'info, Mint>,
    #[account(mut)]
    pub meme_registry: Account<'info, MemeCoinRegistry>,
    #[account(mut)]
    pub contract: Account<'info, TokenContract>,
    #[account(mut)]
    pub owner: Signer<'info>,
    #[account(seeds = [b"zk_vault", user.key().as_ref()], bump)]
    pub vault_account: Account<'info, Vault>,
    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,
    pub rent: Sysvar<'info, Rent>,
}

#[derive(Accounts)]
pub struct GlobalTaxSwap<'info> {
    #[account(mut)]
    pub contract: Account<'info, TokenContract>,
    #[account(mut)]
    pub user: Signer<'info>,
    #[account(mut)]
    pub user_ata: Account<'info, TokenAccount>,
    #[account(mut)]
    pub user_safepump_ata: Account<'info, TokenAccount>,
    #[account(mut)]
    pub vault: Account<'info, TokenAccount>,
    #[account(mut)]
    pub sol_vault: Account<'info, TokenAccount>,
    #[account(mut)]
    pub lp_vault: Account<'info, TokenAccount>,
    #[account(mut)]
    pub badge_vault: Account<'info, TokenAccount>,
    #[account(mut)]
    pub swap_rewards_vault: Account<'info, TokenAccount>,
    #[account(mut)]
    pub mint: Account<'info, Mint>,
    #[account(mut)]
    pub owner: Signer<'info>,
    #[account(mut)]
    pub badge_holders: Account<'info, BadgeHolders>,
    #[account(mut)]
    pub user_swap_data: Account<'info, UserSwapData>,
    #[account(mut)]
    pub reward_distribution: Account<'info, RewardDistribution>,
    #[account(mut)]
    pub pool_state: AccountInfo<'info>,
    #[account(address = raydium_cp_swap::id())]
    pub raydium_program: Program<'info, raydium_cp_swap::program::RaydiumCpSwap>,
    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub rent: Sysvar<'info, Rent>,
}

#[derive(Accounts)]
pub struct TriggerAirdrop<'info> {
    #[account(mut)]
    pub contract: Account<'info, TokenContract>,
    #[account(mut)]
    pub owner: Signer<'info>,
    #[account(seeds = [b"airdrop_registry"], bump)]
    pub airdrop_registry: Account<'info, AirdropRegistry>,
    #[account(mut)]
    pub mint: Account<'info, Mint>,
    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,
    pub associated_token_program: Program<'info, AssociatedToken>,
}
